// Code generated by goctl. DO NOT EDIT.
// Source: zrpc-dois.proto

package server

import (
	"context"

	"zrpc-aula-2/common/pb"
	"zrpc-aula-2/zrpc-dois/internal/logic"
	"zrpc-aula-2/zrpc-dois/internal/svc"
)

type ZrpcDoisServiceServer struct {
	svcCtx *svc.ServiceContext
	__.UnimplementedZrpcDoisServiceServer
}

func NewZrpcDoisServiceServer(svcCtx *svc.ServiceContext) *ZrpcDoisServiceServer {
	return &ZrpcDoisServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *ZrpcDoisServiceServer) ZrpcDoisMethod(ctx context.Context, in *__.ZrpcDoisMethodRequest) (*__.ZrpcDoisMethodResponse, error) {
	l := logic.NewZrpcDoisMethodLogic(ctx, s.svcCtx)
	return l.ZrpcDoisMethod(in)
}
