// Code generated by goctl. DO NOT EDIT.
// Source: zrpc-um.proto

package server

import (
	"context"

	"go-zero-tls/common/pb"
	"go-zero-tls/zrpc-um/internal/logic"
	"go-zero-tls/zrpc-um/internal/svc"
)

type ZrpcUmServiceServer struct {
	svcCtx *svc.ServiceContext
	__.UnimplementedZrpcUmServiceServer
}

func NewZrpcUmServiceServer(svcCtx *svc.ServiceContext) *ZrpcUmServiceServer {
	return &ZrpcUmServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *ZrpcUmServiceServer) ZrpcUmMethod(ctx context.Context, in *__.ZrpcUmMethodRequest) (*__.ZrpcUmMethodResponse, error) {
	l := logic.NewZrpcUmMethodLogic(ctx, s.svcCtx)
	return l.ZrpcUmMethod(in)
}
